(* backslash is used to refer to \ *)
backslash
    = ""
    ;

(* dqoute is used to refer to " *)
dquote
    = ""
    ;

digit
    = "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    ;

uppercase
    = "A"
    | "B"
    | "C"
    | "D"
    | "E"
    | "F"
    | "G"
    | "H"
    | "I"
    | "J"
    | "K"
    | "L"
    | "M"
    | "N"
    | "O"
    | "P"
    | "Q"
    | "R"
    | "S"
    | "T"
    | "U"
    | "V"
    | "W"
    | "X"
    | "Y"
    | "Z"
    ;

lowercase
    = "a"
    | "b"
    | "c"
    | "d"
    | "e"
    | "f"
    | "g"
    | "h"
    | "i"
    | "j"
    | "k"
    | "l"
    | "m"
    | "n"
    | "o"
    | "p"
    | "q"
    | "r"
    | "s"
    | "t"
    | "u"
    | "v"
    | "w"
    | "x"
    | "y"
    | "z"
    ;

(* ascii is used to refer to any US-ASCII character *)
ascii
    = ""
    ;

(* unicode is used to refer to any unicode character with an encoding above 0x7F *)
unicode
    = ""
    ;

character_without_digit
    = uppercase
    | lowercase
    | ""
    | unicode
    ;

character_with_digit
    = digit
    | character_without_digit
    ;