(*
    Single line comment
*)
single_line_comment
    = "//" , { character_with_digit } , [ newline ]
    ;

(*
    Multi line comment
*)
multi_line_comment
    = "/*" , { character_with_digit } , "*/"
    ;